/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package da.application.form.other;

import da.model.HoaDon;
import da.service.HoaDonService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class HoaDonForm extends javax.swing.JPanel {
private HoaDonService hoaDonService = new HoaDonService();
private List<HoaDon> listKhoHang;
    /**
     * Creates new form HoaDonForm
     */
    public HoaDonForm() {
        listKhoHang = new ArrayList<>();
        initComponents();
        loadHoaDonData();
    }
private void loadHoaDonData() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien3.getModel();
    model.setRowCount(0);
    java.util.List<HoaDon> hoaDons = hoaDonService.getListHoaDon();
    int stt = 1;
    for (HoaDon hd : hoaDons) {
        model.addRow(new Object[]{
            stt++,
            hd.getMaHoaDon(),
            hd.getTenKhachHang(),
            hd.getTongTien() != null ? hd.getTongTien().toString() : "0.00",
            hd.getTrangThai(),
            hd.getNgayTao() != null ? hd.getNgayTao().toString() : ""
        });
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialTabbed1 = new da.component.MaterialTabbed();
        jPanel1 = new javax.swing.JPanel();
        crazyPanel5 = new raven.crazypanel.CrazyPanel();
        paymentForm1 = new da.application.form.other.PaymentForm(this);
        crazyPanel7 = new raven.crazypanel.CrazyPanel();
        crazyPanel8 = new raven.crazypanel.CrazyPanel();
        txtSearch3 = new javax.swing.JTextField();
        cmdSearch3 = new javax.swing.JButton();
        cmdExcel3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhanVien3 = new javax.swing.JTable();

        crazyPanel5.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "background:$Table.background;[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20",
            null
        ));
        crazyPanel5.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap,fill,insets 15",
            "[fill]",
            "[grow 0][fill]",
            null
        ));
        crazyPanel5.add(paymentForm1);

        crazyPanel7.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "background:$Table.background;[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20",
            null
        ));
        crazyPanel7.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap,fill,insets 15",
            "[fill]",
            "[grow 0][fill]",
            null
        ));

        crazyPanel8.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "background:$Table.background",
            new String[]{
                "JTextField.placeholderText=Search;background:@background",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1"
            }
        ));
        crazyPanel8.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "",
            "[]push[][]",
            "",
            new String[]{
                "width 200"
            }
        ));
        crazyPanel8.add(txtSearch3);

        cmdSearch3.setText("Search");
        cmdSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSearch3ActionPerformed(evt);
            }
        });
        crazyPanel8.add(cmdSearch3);

        cmdExcel3.setText("Excel");
        crazyPanel8.add(cmdExcel3);

        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        crazyPanel8.add(jButton1);

        crazyPanel7.add(crazyPanel8);

        tblNhanVien3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên Khách Hàng", "Tổng Tiền", "Trạng Thái", "Ngày"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblNhanVien3);

        crazyPanel7.add(jScrollPane4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crazyPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crazyPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crazyPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crazyPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)))
        );

        materialTabbed1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSearch3ActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearch3.getText().trim().toLowerCase();
    
    List<HoaDon> filteredList = new ArrayList<>();
    for (HoaDon hd : listKhoHang) {
        String idStr = String.valueOf(hd.getId());
        String tongTienStr = String.valueOf(hd.getTongTien());
        String ngayTaoStr = hd.getNgayTao() != null ? hd.getNgayTao().toString().toLowerCase() : "";
        if (idStr.contains(keyword) ||
            (hd.getMaHoaDon() != null && hd.getMaHoaDon().toLowerCase().contains(keyword)) ||
            (hd.getTenKhachHang() != null && hd.getTenKhachHang().toLowerCase().contains(keyword)) ||
            tongTienStr.contains(keyword) ||
            ngayTaoStr.contains(keyword)) {
            filteredList.add(hd);
        }
    }
    
    DefaultTableModel model = (DefaultTableModel) tblNhanVien3.getModel();
    model.setRowCount(0);
    
    for (HoaDon hd : filteredList) {
        Object[] row = {
            hd.getId(),
            hd.getMaHoaDon(),
            hd.getTenKhachHang(),
            hd.getNgayTao(),
            hd.getTongTien()
        };
        model.addRow(row);
    }
    
    if (filteredList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn nào phù hợp với từ khóa: " + keyword, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_cmdSearch3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadHoaDonData();
    JOptionPane.showMessageDialog(this, "Dữ liệu đã được làm mới", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed
public JTable getTblNhanVien3() {
        return tblNhanVien3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdExcel3;
    private javax.swing.JButton cmdSearch3;
    private raven.crazypanel.CrazyPanel crazyPanel5;
    private raven.crazypanel.CrazyPanel crazyPanel7;
    private raven.crazypanel.CrazyPanel crazyPanel8;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private da.component.MaterialTabbed materialTabbed1;
    private da.application.form.other.PaymentForm paymentForm1;
    private javax.swing.JTable tblNhanVien3;
    private javax.swing.JTextField txtSearch3;
    // End of variables declaration//GEN-END:variables
}
